version: 1
jobs:
  build:
    image: node:12
    script:
        - npm install
        - npx truffle compile

  # test:
  #   image: node:12
  #   script:
  #       - npm install
  #       - npx truffle test

  deploy_rinkeby_metamask:
    image: node:12
    type:
        name: ethereum/deploy
    script:
        - npm install
        - DEVELOP=TRUE npx truffle migrate --network rinkeby_metamask --reset

        
stages:
  - build_and_test:
      jobs: 
        - build
        # - test
  - deploy:
      jobs:
        - deploy_rinkeby_metamask:
            when: manual
